name: CI/CD Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          REPO=${{ secrets.DOCKERHUB_USER }}/achievka_frontend
          TAG=${{ github.sha }}
          docker build -f Dockerfile \
            -t $REPO:$TAG \
            -t $REPO:latest \
            .
          docker push $REPO:$TAG
          docker push $REPO:latest

      - name: Добавить GitHub в known_hosts
        run: |
          mkdir -p ~/.ssh
          # записываем приватный ключ из секрета
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # пробросим ssh-агент (если планируется использовать нестандартное имя файла)
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          # правильный вызов ssh-keyscan с указанием хоста
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts



      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}
            docker-compose pull frontend
            docker-compose stop frontend   || true
            docker-compose rm -f frontend  || true
            docker-compose up -d frontend
          EOF
