name: CI/CD Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2) Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Сборка Docker-образа и пуш в Docker Hub
      - name: Build and push image
        run: |
          REPO=${{ secrets.DOCKERHUB_USER }}/achievka_frontend
          TAG=${{ github.sha }}
          docker build \
            -f /Dockerfile \
            -t $REPO:$TAG \
            -t $REPO:latest \
            frontend
          docker push $REPO:$TAG
          docker push $REPO:latest

      # 4) Подготовка SSH-ключа
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # 5) Деплой на EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github_actions ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}

            # Обновляем образ сервиса frontend
            docker-compose pull frontend

            # Перезапускаем контейнер
            docker-compose stop frontend   || true
            docker-compose rm -f frontend  || true
            docker-compose up -d frontend
          EOF
